version: "3.4"
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applications_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - combined-network
  quizlet_bot:
    build: ./quizlet_bot
    command: python main.py
    container_name: quizlet_bot
    depends_on:
      - db
    networks:
      - combined-network
networks:
  combined-network:
    driver: bridge